// ==========================================================================
// Scout / Application のダミーデータ
// source       : "scout" | "self-applied"   ← NEW: 応募経路
// status       : スカウト一覧時のステータス  "scout" | "hold" | "decline"
// appStatus    : 応募一覧時のステータス     "applied" | "hired" | "rejected"
// ==========================================================================

export const SCOUTS = [
  // ----- 1: 建設 / スカウト経由 / 応募済 -----
  {
    id: "scout_001",
    source: "scout",
    company: "サンプル建設",
    industry: "建設業",
    jobTitle: "施工管理スタッフ",
    location: "日本全国あり",
    salaryMin: 350,
    salaryMax: 450,
    holidays: 118,
    icon: "🏗",
    iconBg: "#E0EBF7",
    iconColor: "#3565AB",
    status: "scout",
    appStatus: "applied",
    isNew: true,
    receivedAt: "2025-04-30",
    message: "佐藤さんの情報を拝見し、ぜひ当社へ面接にお越しいただきたくご連絡しました。質問などもお気軽にどうぞ。前職での経験を活かしていただけるポジションです。",
    tags: ["未経験OK", "残業少なめ", "賞与年2回", "退職金あり"],
    perks: {
      annualIncome: "400 〜 420万円",
      monthly: "月給30万、時給2,125円",
      holidays: "118日",
      schedule: "土日、祝日+有給（初年度10日）",
      others: "インセンティブあり、夜勤の研修制度、特別休暇14日あり、手当も充実",
    },
    photos: ["🏗", "🏢", "👷‍♂️", "📐", "🚧", "🔧"],
    prPoints: [
      "未経験から成長できる充実の研修制度",
      "全国展開だから希望勤務地で働ける",
      "残業少なめでプライベートも両立",
    ],
  },

  // ----- 2: 歯科 / 自己応募 / 応募済 -----
  {
    id: "scout_002",
    source: "self-applied",
    company: "ABC歯科クリニック",
    industry: "医療・歯科",
    jobTitle: "歯科助手",
    location: "東京都品川区",
    salaryMin: 250,
    salaryMax: 320,
    holidays: 120,
    icon: "🦷",
    iconBg: "#E8F5F0",
    iconColor: "#1D9E75",
    status: "scout",
    appStatus: "applied",
    isNew: true,
    receivedAt: "2025-04-29",
    message: "プロフィールを拝見しました。明るく接遇に強そうな点が当院にぴったりです。未経験から始められるポジションで、資格取得もサポートします。",
    tags: ["未経験OK", "資格取得サポート", "土日祝休み", "残業ほぼなし"],
    perks: {
      annualIncome: "270 〜 320万円",
      monthly: "月給22.5万円〜",
      holidays: "120日",
      schedule: "土日祝休み+有給（初年度10日）",
      others: "制服貸与、健康診断、社員割引（クリーニング無料）",
    },
    photos: ["🦷", "🪥", "👩‍⚕️", "🏥", "💊", "✨"],
    prPoints: [
      "未経験OK・先輩がしっかりサポート",
      "土日祝休みで予定が立てやすい",
      "残業ほぼなし、ワークライフバランス◎",
    ],
  },

  // ----- 3: 運輸 / スカウト経由 / 応募済 -----
  {
    id: "scout_003",
    source: "scout",
    company: "ヤマト運輸",
    industry: "運輸・物流",
    jobTitle: "配達スタッフ",
    location: "日本全国あり",
    salaryMin: 320,
    salaryMax: 420,
    holidays: 118,
    icon: "📦",
    iconBg: "#FFF4E0",
    iconColor: "#D4880A",
    status: "scout",
    appStatus: "applied",
    isNew: false,
    receivedAt: "2025-04-27",
    message: "あなたの体力と人当たりの良さは、お客様と接する配達のお仕事にぴったりです。安心の福利厚生でお迎えします。",
    tags: ["未経験OK", "全国転勤あり", "退職金あり", "資格取得支援"],
    perks: {
      annualIncome: "330 〜 420万円",
      monthly: "月給25.6万円〜",
      holidays: "118日（変形労働時間制）",
      schedule: "シフト制",
      others: "制服貸与、退職金、社員割引、運転免許取得支援",
    },
    photos: ["📦", "🚚", "🛵", "📮", "👷", "🗺"],
    prPoints: [
      "未経験から始められる配達スタッフ",
      "全国に拠点あり、希望地で勤務可能",
      "充実した福利厚生・退職金制度",
    ],
  },

  // ----- 4: アパレル / 自己応募 / 応募済 -----
  {
    id: "scout_004",
    source: "self-applied",
    company: "Fashion MOTA",
    industry: "アパレル・販売",
    jobTitle: "販売スタッフ",
    location: "東京都新宿区",
    salaryMin: 250,
    salaryMax: 320,
    holidays: 105,
    icon: "👗",
    iconBg: "#FCEBEE",
    iconColor: "#D14B6E",
    status: "scout",
    appStatus: "applied",
    isNew: false,
    receivedAt: "2025-04-26",
    message: "あなたの明るさと接客への意欲を見て、ぜひ当ブランドの店頭で活躍していただきたいと思いました。",
    tags: ["社員割引", "未経験OK", "シフト相談可", "賞与あり"],
    perks: {
      annualIncome: "260 〜 320万円",
      monthly: "月給21万円〜",
      holidays: "105日（シフト制）",
      schedule: "週休2日（シフト）",
      others: "社員割引50%、賞与年2回、交通費全額支給",
    },
    photos: ["👗", "👜", "🛍", "👠", "💄", "✨"],
    prPoints: [
      "好きなブランドで働ける喜び",
      "社員割引50%でファッションを楽しめる",
      "シフト柔軟で予定が立てやすい",
    ],
  },

  // ----- 5: 車買取 / スカウト経由 / 結果（内定） -----
  {
    id: "scout_005",
    source: "scout",
    company: "MOTA車買取",
    industry: "車買取・査定",
    jobTitle: "査定スタッフ",
    location: "東京都港区",
    salaryMin: 380,
    salaryMax: 600,
    holidays: 115,
    icon: "🚗",
    iconBg: "#E0EFE6",
    iconColor: "#1D7A4D",
    status: "scout",
    appStatus: "hired",
    isNew: false,
    receivedAt: "2025-04-20",
    message: "車好きなあなたにぴったりのお仕事です。査定スキルは未経験から研修で身につけられます。インセンティブ充実。",
    tags: ["未経験OK", "車好き歓迎", "インセンティブ充実", "資格取得支援"],
    perks: {
      annualIncome: "400 〜 600万円（インセンティブ込）",
      monthly: "月給28万円〜+インセンティブ",
      holidays: "115日",
      schedule: "週休2日（シフト制）",
      others: "インセンティブ最大月20万、研修制度、社用車貸与",
    },
    photos: ["🚗", "🚙", "🔑", "📋", "💼", "🏢"],
    prPoints: [
      "車好きが集まる職場で楽しく働ける",
      "実力次第で年収600万円も可能",
      "未経験者向けの研修制度が充実",
    ],
  },

  // ----- 6: 介護 / 自己応募 / 結果（不採用） -----
  {
    id: "scout_006",
    source: "self-applied",
    company: "ケアハウスさくら",
    industry: "介護・福祉",
    jobTitle: "介護スタッフ",
    location: "東京都世田谷区",
    salaryMin: 300,
    salaryMax: 380,
    holidays: 110,
    icon: "🌸",
    iconBg: "#F8E6F0",
    iconColor: "#A04E80",
    status: "scout",
    appStatus: "rejected",
    isNew: false,
    receivedAt: "2025-04-15",
    message: "あたたかい対応ができそうなあなたに、入居者様と日々を過ごしていただきたいです。資格取得もサポートします。",
    tags: ["未経験OK", "資格取得支援", "夜勤手当", "退職金あり"],
    perks: {
      annualIncome: "310 〜 380万円",
      monthly: "月給23万円〜",
      holidays: "110日",
      schedule: "シフト制（夜勤あり）",
      others: "夜勤手当、資格手当、退職金制度、社員食堂",
    },
    photos: ["🌸", "👵", "👴", "🤝", "🏥", "☕"],
    prPoints: [
      "未経験から介護福祉士を目指せる",
      "資格取得を会社が全力サポート",
      "夜勤手当・各種手当が充実",
    ],
  },
];
