// ==========================================================================
// Scout (スカウト) のダミーデータ
// status        : スカウト一覧でのステータス  "scout" | "hold" | "decline"
// appStatus     : 応募一覧でのステータス     "applied" | "hired" | "rejected"
// ==========================================================================

export const SCOUTS = [
  {
    id: "scout_001",
    source: "scout",     // ← この行を追加
    company: "サンプル建設",
    industry: "建設業",
    jobTitle: "施工管理スタッフ",
    location: "日本全国あり",
    salaryMin: 350,
    salaryMax: 450,
    holidays: 118,
    icon: "🏗",
    iconBg: "#E0EBF7",
    iconColor: "#3565AB",
    status: "scout",
    appStatus: "applied",
    isNew: true,
    receivedAt: "2025-04-30",
    message: "佐藤さんの情報を拝見し、ぜひ当社へ面接にお越しいただきたくご連絡しました。質問などもお気軽にどうぞ。前職での経験を活かしていただけるポジションです。",
    tags: ["未経験OK", "残業少なめ", "賞与年2回", "退職金あり"],
    perks: {
      annualIncome: "400 〜 420万円",
      monthly: "月給30万、時給2,125円",
      holidays: "118日",
      schedule: "土日、祝日+有給（初年度10日）",
      others: "インセンティブあり、夜勤の研修制度、特別休暇14日あり、手当も充実",
    },
    photos: ["🏗", "🏢", "👷‍♂️", "📐", "🚧", "🔧"],
    prPoints: [
      "未経験から成長できる充実の研修制度",
      "全国展開だから希望勤務地で働ける",
      "残業少なめでプライベートも両立",
    ],
    voiceFromEmployee: {
      name: "Tさん（28歳・男性）",
      role: "施工管理 / 入社2年目",
      content: "前職は飲食業でしたが、未経験から入社して2年で現場を任せてもらえるようになりました。先輩方が丁寧に教えてくださるので、安心して成長できる環境です。",
    },
  },
  {
    id: "scout_002",
    source: "self-applied",     // ← この行を追加
    company: "ABC歯科クリニック",
    industry: "医療・歯科",
    jobTitle: "歯科助手",
    location: "東京都内勤務",
    salaryMin: 280,
    salaryMax: 350,
    holidays: 120,
    icon: "🦷",
    iconBg: "#E8F4D9",
    iconColor: "#5A8B2D",
    status: "scout",
    appStatus: "applied",
    isNew: true,
    receivedAt: "2025-04-29",
    message: "未経験から始められる方を募集しています。当院は研修制度が充実しており、長く働けるアットホームな職場です。ぜひ面接にお越しください。",
    tags: ["未経験OK", "土日休み", "研修充実", "アットホーム"],
    perks: {
      annualIncome: "280 〜 350万円",
      monthly: "月給22万円〜",
      holidays: "120日",
      schedule: "日曜+平日1日",
      others: "交通費全額支給、社保完備、昇給年1回",
    },
    photos: ["🦷", "🏥", "👩‍⚕️", "💉", "📋", "🧑‍🦰"],
    prPoints: [
      "土日も休みでプライベートを確保",
      "充実の研修で未経験から正社員へ",
      "アットホームな雰囲気で長く働ける",
    ],
    voiceFromEmployee: {
      name: "Mさん（26歳・女性）",
      role: "歯科助手 / 入社3年目",
      content: "院長やスタッフの皆さんが優しくて、初日から働きやすかったです。患者さんに『ありがとう』と言ってもらえると本当にやりがいを感じます。",
    },
  },
  {
    id: "scout_003",
    source: "scout",     // ← この行を追加
    company: "ヤマト運輸",
    industry: "運輸・物流",
    jobTitle: "配送スタッフ・乗務員",
    location: "全国あり",
    salaryMin: 400,
    salaryMax: 420,
    holidays: 118,
    icon: "🚚",
    iconBg: "#FEF3D6",
    iconColor: "#B5832A",
    status: "scout",
    appStatus: "hired",
    isNew: false,
    receivedAt: "2025-04-25",
    message: "当社では普通自動車免許をお持ちの方を積極採用中です。安定した収入と充実した福利厚生をご用意しています。面接にお越しください。",
    tags: ["要普免", "賞与年2回", "全国転勤", "資格手当"],
    perks: {
      annualIncome: "400 〜 420万円",
      monthly: "月給28万円+各種手当",
      holidays: "118日",
      schedule: "シフト制、4週8休",
      others: "資格取得支援あり、寮・社宅制度あり",
    },
    photos: ["🚚", "📦", "🛣", "👷", "🏬", "🚛"],
    prPoints: [
      "資格手当・各種手当で安定した収入",
      "資格取得支援で次のキャリアへ",
      "寮・社宅完備で住居の心配なし",
    ],
    voiceFromEmployee: {
      name: "Kさん（32歳・男性）",
      role: "配送スタッフ / 入社5年目",
      content: "未経験で入社しましたが、運転も丁寧に教えてもらえました。手当も充実していて、家族を養うにも安心できる職場です。",
    },
  },
  {
    id: "scout_004",
    source: "self-applied",     // ← この行を追加
    company: "Fashion MOTA",
    industry: "アパレル販売",
    jobTitle: "販売スタッフ・東京都板橋区",
    location: "東京都板橋区",
    salaryMin: 250,
    salaryMax: 300,
    holidays: 105,
    icon: "👔",
    iconBg: "#FDE6F0",
    iconColor: "#B53A78",
    status: "hold",
    appStatus: "applied",
    isNew: false,
    receivedAt: "2025-04-20",
    message: "明るい接客が得意な方を募集しています。社割でブランド商品を購入できる嬉しい特典あり。ぜひ一度お話を聞かせてください。",
    tags: ["社割あり", "髪型自由", "ブランクOK"],
    perks: {
      annualIncome: "250 〜 300万円",
      monthly: "月給21万円〜+販売インセンティブ",
      holidays: "105日",
      schedule: "シフト制",
      others: "社員割引50%、研修制度あり",
    },
    photos: ["👔", "👗", "🛍", "💄", "🪞", "🏬"],
    prPoints: [
      "社割50%でお得にお買い物",
      "髪型・ネイル自由で自分らしく働ける",
      "ブランクOKで復職もしやすい",
    ],
    voiceFromEmployee: {
      name: "Yさん（24歳・女性）",
      role: "販売スタッフ / 入社2年目",
      content: "ファッションが好きで入社しました。社割で好きなブランドを楽しみつつ、お客様に喜んでもらえる仕事は本当に楽しいです。",
    },
  },
  {
    id: "scout_005",
    source: "scout",     // ← この行を追加
    company: "車買取センター東京",
    industry: "車買取",
    jobTitle: "買取査定スタッフ",
    location: "東京都江東区",
    salaryMin: 380,
    salaryMax: 500,
    holidays: 110,
    icon: "🚗",
    iconBg: "#E0F2F8",
    iconColor: "#1D7AAB",
    status: "scout",
    appStatus: "applied",
    isNew: true,
    receivedAt: "2025-04-30",
    message: "車が好きな方歓迎！未経験から始められ、頑張り次第で年収500万も可能です。インセンティブ制度が充実しています。",
    tags: ["未経験OK", "高収入", "車好き歓迎", "インセン充実"],
    perks: {
      annualIncome: "380 〜 500万円",
      monthly: "月給28万円+業績インセンティブ",
      holidays: "110日",
      schedule: "シフト制、月8〜9日休み",
      others: "社用車貸与、資格取得支援、研修制度充実",
    },
    photos: ["🚗", "🔑", "💼", "🚘", "📊", "🏢"],
    prPoints: [
      "頑張り次第で年収500万円も可能",
      "車好きが集まる活気ある職場",
      "未経験から始められる手厚い研修",
    ],
    voiceFromEmployee: {
      name: "Sさん（29歳・男性）",
      role: "買取査定スタッフ / 入社3年目",
      content: "もともと車が好きで未経験から入社しました。査定スキルが身につくと年収も上がっていき、3年目で500万を超えました。",
    },
  },
  {
    id: "scout_006",
    source: "self-applied",     // ← この行を追加
    company: "ケアサポート神奈川",
    industry: "介護",
    jobTitle: "介護スタッフ",
    location: "神奈川県横浜市",
    salaryMin: 270,
    salaryMax: 380,
    holidays: 115,
    icon: "🧑‍🦳",
    iconBg: "#F0E8FA",
    iconColor: "#6B4DAA",
    status: "decline",
    appStatus: "rejected",
    isNew: false,
    receivedAt: "2025-04-18",
    message: "未経験から介護のプロを目指せる環境です。資格取得支援制度あり、夜勤手当も充実しています。ぜひお話させてください。",
    tags: ["未経験OK", "資格取得支援", "夜勤手当", "正社員登用"],
    perks: {
      annualIncome: "270 〜 380万円",
      monthly: "月給22万円+夜勤手当",
      holidays: "115日",
      schedule: "シフト制、4週8休",
      others: "資格取得支援、社員寮あり、賞与年2回",
    },
    photos: ["🧑‍🦳", "🏥", "👨‍⚕️", "🌷", "🏠", "🧑‍🤝‍🧑"],
    prPoints: [
      "資格取得支援で介護のプロへ成長",
      "夜勤手当で月収アップ",
      "ご利用者様との温かい時間",
    ],
    voiceFromEmployee: {
      name: "Aさん（31歳・女性）",
      role: "介護スタッフ / 入社4年目",
      content: "未経験で不安でしたが、資格取得もサポートしてもらい、介護福祉士になれました。ご利用者様の笑顔が何よりやりがいです。",
    },
  },
];
