// ==========================================================================
// Scout (スカウト) のダミーデータ
// ==========================================================================

export const SCOUTS = [
  {
    id: "scout_001",
    company: "サンプル建設",
    industry: "建設業",
    jobTitle: "施工管理スタッフ",
    location: "日本全国あり",
    salaryMin: 350,
    salaryMax: 450,
    holidays: 118,
    icon: "🏗",
    iconBg: "#E0EBF7",
    iconColor: "#3565AB",
    status: "scout", // "scout" | "hold" | "decline"
    isNew: true,
    receivedAt: "2025-04-30",
    message: "佐藤さんの情報を拝見し、ぜひ当社へ面接にお越しいただきたくご連絡しました。質問などもお気軽にどうぞ。前職での経験を活かしていただけるポジションです。",
    tags: ["未経験OK", "残業少なめ", "賞与年2回", "退職金あり"],
    perks: {
      annualIncome: "400 〜 420万円",
      monthly: "月給30万、時給2,125円",
      holidays: "118日",
      schedule: "土日、祝日+有給（初年度10日）",
      others: "インセンティブあり、夜勤の研修制度、特別休暇14日あり、手当も充実",
    },
    photos: ["🏗", "🏢", "👷‍♂️", "📐", "🚧", "🔧"],
  },
  {
    id: "scout_002",
    company: "ABC歯科クリニック",
    industry: "医療・歯科",
    jobTitle: "歯科助手",
    location: "東京都内勤務",
    salaryMin: 280,
    salaryMax: 350,
    holidays: 120,
    icon: "🦷",
    iconBg: "#E8F4D9",
    iconColor: "#5A8B2D",
    status: "scout",
    isNew: true,
    receivedAt: "2025-04-29",
    message: "未経験から始められる方を募集しています。当院は研修制度が充実しており、長く働けるアットホームな職場です。ぜひ面接にお越しください。",
    tags: ["未経験OK", "土日休み", "研修充実", "アットホーム"],
    perks: {
      annualIncome: "280 〜 350万円",
      monthly: "月給22万円〜",
      holidays: "120日",
      schedule: "日曜+平日1日",
      others: "交通費全額支給、社保完備、昇給年1回",
    },
    photos: ["🦷", "🏥", "👩‍⚕️", "💉", "📋", "🧑‍🦰"],
  },
  {
    id: "scout_003",
    company: "ヤマト運輸",
    industry: "運輸・物流",
    jobTitle: "配送スタッフ・乗務員",
    location: "全国あり",
    salaryMin: 400,
    salaryMax: 420,
    holidays: 118,
    icon: "🚚",
    iconBg: "#FEF3D6",
    iconColor: "#B5832A",
    status: "scout",
    isNew: false,
    receivedAt: "2025-04-25",
    message: "当社では普通自動車免許をお持ちの方を積極採用中です。安定した収入と充実した福利厚生をご用意しています。面接にお越しください。",
    tags: ["要普免", "賞与年2回", "全国転勤", "資格手当"],
    perks: {
      annualIncome: "400 〜 420万円",
      monthly: "月給28万円+各種手当",
      holidays: "118日",
      schedule: "シフト制、4週8休",
      others: "資格取得支援あり、寮・社宅制度あり",
    },
    photos: ["🚚", "📦", "🛣", "👷", "🏬", "🚛"],
  },
  {
    id: "scout_004",
    company: "Fashion MOTA",
    industry: "アパレル販売",
    jobTitle: "販売スタッフ・東京都板橋区",
    location: "東京都板橋区",
    salaryMin: 250,
    salaryMax: 300,
    holidays: 105,
    icon: "👔",
    iconBg: "#FDE6F0",
    iconColor: "#B53A78",
    status: "hold",
    isNew: false,
    receivedAt: "2025-04-20",
    message: "明るい接客が得意な方を募集しています。社割でブランド商品を購入できる嬉しい特典あり。ぜひ一度お話を聞かせてください。",
    tags: ["社割あり", "髪型自由", "ブランクOK"],
    perks: {
      annualIncome: "250 〜 300万円",
      monthly: "月給21万円〜+販売インセンティブ",
      holidays: "105日",
      schedule: "シフト制",
      others: "社員割引50%、研修制度あり",
    },
    photos: ["👔", "👗", "🛍", "💄", "🪞", "🏬"],
  },
  {
    id: "scout_005",
    company: "車買取センター東京",
    industry: "車買取",
    jobTitle: "買取査定スタッフ",
    location: "東京都江東区",
    salaryMin: 380,
    salaryMax: 500,
    holidays: 110,
    icon: "🚗",
    iconBg: "#E0F2F8",
    iconColor: "#1D7AAB",
    status: "scout",
    isNew: true,
    receivedAt: "2025-04-30",
    message: "車が好きな方歓迎！未経験から始められ、頑張り次第で年収500万も可能です。インセンティブ制度が充実しています。",
    tags: ["未経験OK", "高収入", "車好き歓迎", "インセン充実"],
    perks: {
      annualIncome: "380 〜 500万円",
      monthly: "月給28万円+業績インセンティブ",
      holidays: "110日",
      schedule: "シフト制、月8〜9日休み",
      others: "社用車貸与、資格取得支援、研修制度充実",
    },
    photos: ["🚗", "🔑", "💼", "🚘", "📊", "🏢"],
  },
  {
    id: "scout_006",
    company: "ケアサポート神奈川",
    industry: "介護",
    jobTitle: "介護スタッフ",
    location: "神奈川県横浜市",
    salaryMin: 270,
    salaryMax: 380,
    holidays: 115,
    icon: "🧑‍🦳",
    iconBg: "#F0E8FA",
    iconColor: "#6B4DAA",
    status: "decline",
    isNew: false,
    receivedAt: "2025-04-18",
    message: "未経験から介護のプロを目指せる環境です。資格取得支援制度あり、夜勤手当も充実しています。ぜひお話させてください。",
    tags: ["未経験OK", "資格取得支援", "夜勤手当", "正社員登用"],
    perks: {
      annualIncome: "270 〜 380万円",
      monthly: "月給22万円+夜勤手当",
      holidays: "115日",
      schedule: "シフト制、4週8休",
      others: "資格取得支援、社員寮あり、賞与年2回",
    },
    photos: ["🧑‍🦳", "🏥", "👨‍⚕️", "🌷", "🏠", "🧑‍🤝‍🧑"],
  },
];
